### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by alexkwolfe**

### CODE REVIEW

**Comment by ros3bud** [comment]
So, just to be clear - I thought title, firstname and lastname should be available so that someone could pass this type of data in, for example, text: 

Dear {{title}} {{lastname}}, 

etc etc.

**Comment by ros3bud** [comment]
But what if someone did want to map a value to title and then include it in the outgoing email?

**Comment by ros3bud** [comment]
Ok, this makes sense - thanks for the clarification. Shall I merge in the changes?

**Comment by alexkwolfe** [comment]
Up to you.

**Pull request merged**
